/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Main.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
/**
 *
 * @author root
 */
public class Uebersicht extends javax.swing.JFrame {
    
    private static JTextField jTextField2 = new JTextField();
    private static JTextField jTextField3 = new JTextField();
    private static JTextField jTextField4 = new JTextField();
    private static JTextField jTextField5 = new JTextField();
    private static JTextField jTextField6 = new JTextField();
    private static JTextField jTextField7 = new JTextField();
    private static JTextField jTextField8 = new JTextField();
    private static JTextField jTextField9 = new JTextField();
    private static JTextField jTextField10 = new JTextField();
    static JTextField[] Log = {jTextField2,jTextField3,jTextField4,jTextField5,jTextField6,jTextField7,jTextField8,jTextField9,jTextField10};
    public static boolean istda = false;
    private static JButton AnAusKnopf = new JButton();

    /**
     * Creates new form Uebersicht
     */
    public Uebersicht() {
        initComponents();
        
        getContentPane().removeAll();
        
        setTitle("LUMA");
        
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));

        jTextField1.setText("Pumpe ist Aus  ");
        jTextField1.setBackground(Color.red);
        jTextField1.setFont(new Font("Dialog", Font.BOLD, 20));
        jTextField1.setEditable(false);
        jPanel1.add(jTextField1);
        AnAusKnopf.addActionListener(UK);
        
        for (JTextField i : Log) {
            jPanel1.add(i);
        }
        getContentPane().add(jPanel1);
        getContentPane().add(AnAusKnopf);

        pack();
        
        istda = true;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollBar1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setLayout(new java.awt.GridLayout());

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);

        getContentPane().add(jPanel1);
        getContentPane().add(jScrollBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uebersicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uebersicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uebersicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uebersicht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uebersicht().setVisible(true);
            }
        });
        Manager M = new Manager();
        M.Steuerung();
    }
    
    public static void PumpeAnUI (int i) {
        if (i == 0)
            jTextField1.setText("Pumpe ist An   ");
        else
            jTextField1.setText("Pumpe ist An (Knopf)");
        jTextField1.setBackground(Color.green);
    }
    public static void PumpeAusUI () {

        jTextField1.setText("Pumpe ist Aus  ");
        jTextField1.setBackground(Color.red);
    }
    public static void newLog (String newLog) {
        for (javax.swing.JTextField i : Log) {
            String oldText = i.getText();
            i.setText(newLog);
            newLog = oldText;
        }
        
    }
    
    private class UIKnopf implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            if(Heizungsobjekt.Pumpe.getIstAn())
                Heizungsobjekt.Pumpe.ausschalten(1);
            else
                Heizungsobjekt.Pumpe.anschalten(1);
        }
    }
    UIKnopf UK = new UIKnopf();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel jPanel1;
    private static javax.swing.JScrollBar jScrollBar1;
    private static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
